import { CalendarCheck, Camera, Phone } from "lucide-react";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { pageMetadata } from "@/lib/metadata";
import { siteConfig } from "@/lib/site";

export const metadata = pageMetadata({ title: "Contact Power Now Service", description: "Call Power Now Service or book an estimate for load bank repair and electrical service in North Houston.", path: "/contact" });

export default function ContactPage() {
  return <main><section className="page-hero dark-section"><div className="shell"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Contact" }]} /><span className="hero-kicker">No lead form. No stored customer data.</span><h1>Book the Estimate or Call Directly</h1><p>Choose the calendar for a planned estimate conversation or call Power Now Service at the only published number below.</p></div></section><section className="content-section"><div className="shell"><div className="contact-actions"><article className="contact-method"><CalendarCheck size={34} aria-hidden="true" /><h2>Book an Estimate</h2><p>Choose a time through the official Power Now Service Calendly page. The website does not collect or store your information.</p><a className="button button-primary" href={siteConfig.bookingUrl}>Open the Booking Calendar</a></article><article className="contact-method"><Phone size={34} aria-hidden="true" /><h2>Call {siteConfig.phoneDisplay}</h2><p>Call to discuss the equipment, property, service area, symptoms, access, and the next useful step.</p><a className="button button-outline" href={siteConfig.phoneHref}>Call Now</a></article></div></div></section><section className="content-section surface-section"><div className="shell two-column-content"><div><span className="section-label">Prepare useful information</span><h2>Help the estimate start closer to the actual problem.</h2><p>Do not open or approach energized equipment solely to gather information. Share only what can be documented safely.</p></div><ul className="check-rows"><li><Camera size={19} aria-hidden="true" /> Equipment nameplate and full-cabinet photo</li><li><Camera size={19} aria-hidden="true" /> Visible damage or displayed fault information</li><li><Camera size={19} aria-hidden="true" /> Location and safe-access constraints</li><li><Camera size={19} aria-hidden="true" /> What changed and when the symptom began</li></ul></div></section></main>;
}
